name: barbers

version: 0.3.2+31

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  get_storage:
  connectivity:
  cached_network_image:
  logger:
  dio:
  retrofit:
  flutter_svg:
  supercharged: 
  auto_size_text:
  smooth_star_rating:
  image_picker:
  photo_view:
  mask_text_input_formatter:
  path_provider:
  permission_handler:
  local_auth:
  pin_code_fields:
  url_launcher:
  intl:
  firebase_messaging:
  flutter_local_notifications:
  
dependency_overrides: 
  analyzer: '0.39.14'

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  lint:
  build_runner:
  json_serializable:
  retrofit_generator:

flutter:
  uses-material-design: true
  assets:
    # Images
    - assets/images/
    # Images
    - assets/icons/
    #Fonts
    - assets/fonts/

flutter_intl:
  enabled: true
  main_locale: ru
  class_name: Strings